[project]
name = "dota-localisation-changer"
version = "1.0.0"
description = ""
authors = [
    {name = "r41ngee",email = "r41ngee@yandex.ru"}
]
readme = "README.md"
requires-python = ">=3.11, <3.14"
dependencies = [
    "altgraph (==0.17.4)",
    "art (==6.4)",
    "auto-py-to-exe (==2.46.0)",
    "bottle (==0.13.2)",
    "bottle-websocket (==0.2.9)",
    "cachetools (==5.5.2)",
    "certifi (==2025.1.31)",
    "cffi (==1.17.1)",
    "charset-normalizer (==3.4.1)",
    "colorama (==0.4.6)",
    "eel (==0.18.1)",
    "future (==1.0.0)",
    "gevent (==24.11.1)",
    "gevent-websocket (==0.10.1)",
    "greenlet (==3.1.1)",
    "idna (==3.10)",
    "isort (==6.0.1)",
    "linkify-it-py (==2.0.3)",
    "markdown-it-py (==3.0.0)",
    "mdit-py-plugins (==0.4.2)",
    "mdurl (==0.1.2)",
    "packaging (==24.2)",
    "pefile (==2023.2.7)",
    "pip-review (==1.3.0)",
    "platformdirs (==4.3.7)",
    "pycparser (==2.22)",
    "pygments (==2.19.1)",
    "pyinstaller (==6.12.0)",
    "pyinstaller-hooks-contrib (==2025.2)",
    "pyparsing (==3.2.3)",
    "pywin32-ctypes (==0.2.3)",
    "requests (==2.32.3)",
    "rich (==14.0.0)",
    "tabulate (==0.9.0)",
    "textual (==3.0.1)",
    "tqdm (==4.67.1)",
    "typing-extensions (==4.13.1)",
    "uc-micro-py (==1.0.3)",
    "urllib3 (==2.3.0)",
    "zope-event (==5.0)",
    "zope-interface (==7.2)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
